import seedProducts from '../data/seed-products.json'

const categories = new Set(['数码', '学习', '生活', '运动', '影音'])
const imageTypes = new Map([['image/jpeg', 'jpg'], ['image/png', 'png'], ['image/webp', 'webp'], ['image/gif', 'gif']])
const schema = [
  `CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY NOT NULL, title TEXT NOT NULL, category TEXT NOT NULL, description TEXT NOT NULL, price INTEGER NOT NULL, condition TEXT NOT NULL, campus TEXT NOT NULL, seller TEXT NOT NULL, seller_id TEXT, image TEXT NOT NULL, tags_json TEXT NOT NULL, posted_at TEXT NOT NULL, created_at TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'shared')`,
  `CREATE TABLE IF NOT EXISTS user_favorites (user_id TEXT NOT NULL, product_id TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(user_id, product_id))`,
  `CREATE TABLE IF NOT EXISTS user_cart_items (user_id TEXT NOT NULL, product_id TEXT NOT NULL, quantity INTEGER NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(user_id, product_id))`,
  `CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY NOT NULL, user_id TEXT, payload_json TEXT NOT NULL, created_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS store_meta (key TEXT PRIMARY KEY NOT NULL, value TEXT NOT NULL, updated_at TEXT NOT NULL)`,
]
const now = () => new Date().toISOString()
const clean = (value, length) => String(value || '').trim().slice(0, length)
const parseTags = (value) => (Array.isArray(value) ? value : String(value || '').split(/[·、,，]/)).map((item) => String(item).trim()).filter(Boolean).slice(0, 4)
function json(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: { 'Cache-Control': 'no-store', 'Content-Type': 'application/json; charset=utf-8' } }) }
function validate(payload) {
  const result = { title: clean(payload.title, 80), description: clean(payload.description, 1000), category: clean(payload.category, 10), condition: clean(payload.condition, 30) || '成色待确认', price: Math.round(Number(payload.price)), tags: parseTags(payload.tags) }
  if (result.title.length < 2 || result.description.length < 4) throw new Error('请补全商品标题和描述。')
  if (!categories.has(result.category)) throw new Error('请选择有效的商品分类。')
  if (!Number.isFinite(result.price) || result.price <= 0 || result.price > 1_000_000) throw new Error('请输入有效价格。')
  return result
}
function mapProduct(row, userId) { return { id: row.id, title: row.title, category: row.category, description: row.description, price: Number(row.price), condition: row.condition, campus: row.campus, seller: row.seller, image: row.image, tags: parseTags(JSON.parse(row.tags_json || '[]')), postedAt: row.posted_at, isOwner: row.seller_id === userId } }
function insertProduct(db, product, source) { return db.prepare('INSERT OR IGNORE INTO products (id,title,category,description,price,condition,campus,seller,seller_id,image,tags_json,posted_at,created_at,source) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(product.id, product.title, product.category, product.description, product.price, product.condition, product.campus, product.seller, product.sellerId || null, product.image, JSON.stringify(product.tags), product.postedAt, product.createdAt || now(), source) }
async function ensure(env) {
  if (!env.DB) throw new Error('多用户数据服务要求绑定 D1 数据库。')
  const db = env.DB; await db.batch(schema.map((sql) => db.prepare(sql)))
  const seeded = await db.prepare("SELECT value FROM store_meta WHERE key='seed_version'").first()
  if (!seeded) { const at = now(); const items = seedProducts.map((p) => insertProduct(db, { ...p, sellerId: null, createdAt: at }, 'seed')); items.push(db.prepare("INSERT INTO store_meta(key,value,updated_at) VALUES('seed_version','1',?)").bind(at)); await db.batch(items) }
  return db
}
async function snapshot(env, userId) {
  const db = await ensure(env)
  const [products, favorites, cart, orders, meta] = await Promise.all([
    db.prepare('SELECT * FROM products ORDER BY created_at DESC').all(),
    db.prepare('SELECT product_id FROM user_favorites WHERE user_id=? ORDER BY updated_at DESC').bind(userId).all(),
    db.prepare('SELECT product_id,quantity FROM user_cart_items WHERE user_id=? ORDER BY updated_at DESC').bind(userId).all(),
    db.prepare('SELECT payload_json FROM orders WHERE user_id=? ORDER BY created_at DESC').bind(userId).all(),
    db.prepare("SELECT value FROM store_meta WHERE key='shared_updated_at'").first(),
  ])
  return { products: products.results.map((row) => mapProduct(row, userId)), favorites: favorites.results.map((row) => row.product_id), cart: Object.fromEntries(cart.results.map((row) => [row.product_id, Number(row.quantity)])), orders: orders.results.map((row) => { try { return JSON.parse(row.payload_json) } catch { return null } }).filter(Boolean), updatedAt: meta?.value || now() }
}
async function touch(db) { const at = now(); await db.prepare("INSERT INTO store_meta(key,value,updated_at) VALUES('shared_updated_at',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(at, at).run() }
async function persistImage(env, dataUrl) {
  if (typeof dataUrl !== 'string' || !dataUrl.startsWith('data:image/')) return clean(dataUrl, 2000) || '/products/lamp.jpg'
  const match = dataUrl.match(/^data:([^;,]+);base64,([A-Za-z0-9+/=]+)$/); if (!match || !imageTypes.has(match[1])) throw new Error('图片格式无法识别。')
  const binary = atob(match[2]); if (binary.length > 2.5 * 1024 * 1024) throw new Error('图片请控制在 2.5 MB 以内。'); if (!env.MEDIA) throw new Error('图片存储尚未绑定。')
  const key = `listing-${crypto.randomUUID()}.${imageTypes.get(match[1])}`; await env.MEDIA.put(key, Uint8Array.from(binary, (c) => c.charCodeAt(0)), { httpMetadata: { contentType: match[1] } }); return `/api/media/${encodeURIComponent(key)}`
}
async function createProduct(request, env, user) { const payload = await request.json(); const product = { id: `user-${Date.now()}-${crypto.randomUUID().slice(0, 8)}`, ...validate(payload), campus: '待与买家协商', seller: user.username, sellerId: user.id, image: await persistImage(env, payload.image), postedAt: '刚刚发布', createdAt: now() }; const db = await ensure(env); await db.batch([insertProduct(db, product, 'shared')]); await touch(db); return json({ product: { ...product, sellerId: undefined, isOwner: true }, store: await snapshot(env, user.id) }, 201) }
async function removeProduct(env, id, user) { const db = await ensure(env); const product = await db.prepare('SELECT image,seller_id FROM products WHERE id=?').bind(id).first(); if (!product) return json({ message: '商品不存在或已被删除。' }, 404); if (product.seller_id !== user.id) return json({ message: '只能删除自己发布的商品。' }, 403); await db.batch([db.prepare('DELETE FROM products WHERE id=?').bind(id), db.prepare('DELETE FROM user_favorites WHERE product_id=?').bind(id), db.prepare('DELETE FROM user_cart_items WHERE product_id=?').bind(id)]); if (env.MEDIA && product.image?.startsWith('/api/media/')) await env.MEDIA.delete(decodeURIComponent(product.image.slice(11))); await touch(db); return json({ store: await snapshot(env, user.id) }) }
async function favorite(request, env, id, user) { const db = await ensure(env); const enabled = Boolean((await request.json()).favorite); if (enabled) await db.prepare('INSERT OR REPLACE INTO user_favorites(user_id,product_id,updated_at) VALUES(?,?,?)').bind(user.id, id, now()).run(); else await db.prepare('DELETE FROM user_favorites WHERE user_id=? AND product_id=?').bind(user.id, id).run(); await touch(db); return json({ store: await snapshot(env, user.id) }) }
async function cart(request, env, id, user) { const db = await ensure(env); const quantity = Math.max(0, Math.min(5, Math.round(Number((await request.json()).quantity) || 0))); if (quantity) await db.prepare('INSERT INTO user_cart_items(user_id,product_id,quantity,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET quantity=excluded.quantity,updated_at=excluded.updated_at').bind(user.id, id, quantity, now()).run(); else await db.prepare('DELETE FROM user_cart_items WHERE user_id=? AND product_id=?').bind(user.id, id).run(); await touch(db); return json({ store: await snapshot(env, user.id) }) }
async function order(request, env, user) { const input = await request.json(); const pickup = clean(input.pickup, 80); const contactTime = clean(input.contactTime, 80); if (!pickup || !contactTime) return json({ message: '请补全交接地点和联系时间。' }, 400); const db = await ensure(env); const rows = await db.prepare('SELECT p.*,c.quantity FROM user_cart_items c JOIN products p ON p.id=c.product_id WHERE c.user_id=?').bind(user.id).all(); const items = rows.results.map((row) => ({ product: mapProduct(row, user.id), quantity: Number(row.quantity) })); if (!items.length) return json({ message: '交易清单为空。' }, 400); const created = now(); const value = { id: `ECHO-${Date.now().toString().slice(-8)}-${crypto.randomUUID().slice(0, 4).toUpperCase()}`, createdAt: new Date().toLocaleString('zh-CN', { hour12: false, timeZone: 'Asia/Shanghai' }), total: items.reduce((sum, item) => sum + item.product.price * item.quantity, 0), status: '待与卖家确认', pickup, contactTime, items }; await db.batch([db.prepare('INSERT INTO orders(id,user_id,payload_json,created_at) VALUES(?,?,?,?)').bind(value.id, user.id, JSON.stringify(value), created), db.prepare('DELETE FROM user_cart_items WHERE user_id=?').bind(user.id)]); await touch(db); return json({ order: value, store: await snapshot(env, user.id) }, 201) }
async function bootstrap(request, env, user) { const payload = await request.json(); const db = await ensure(env); const statements = []; const at = now(); for (const id of (payload.favorites || []).slice(0, 200)) statements.push(db.prepare('INSERT OR IGNORE INTO user_favorites(user_id,product_id,updated_at) VALUES(?,?,?)').bind(user.id, clean(id, 100), at)); for (const [id, raw] of Object.entries(payload.cart || {}).slice(0, 200)) { const q = Math.max(0, Math.min(5, Math.round(Number(raw) || 0))); if (q) statements.push(db.prepare('INSERT OR REPLACE INTO user_cart_items(user_id,product_id,quantity,updated_at) VALUES(?,?,?,?)').bind(user.id, clean(id, 100), q, at)) } for (const value of (payload.orders || []).slice(0, 50)) if (value?.id) statements.push(db.prepare('INSERT OR IGNORE INTO orders(id,user_id,payload_json,created_at) VALUES(?,?,?,?)').bind(clean(value.id, 100), user.id, JSON.stringify(value), at)); if (statements.length) await db.batch(statements); return json({ store: await snapshot(env, user.id), imported: true }) }

export async function handleStoreApi(request, env, user, url) { try { if (url.pathname === '/api/store' && request.method === 'GET') return json({ store: await snapshot(env, user.id) }); if (url.pathname === '/api/store/bootstrap' && request.method === 'POST') return bootstrap(request, env, user); if (url.pathname === '/api/products' && request.method === 'POST') return createProduct(request, env, user); if (url.pathname.startsWith('/api/products/') && request.method === 'DELETE') return removeProduct(env, decodeURIComponent(url.pathname.slice(14)), user); if (url.pathname.startsWith('/api/favorites/') && request.method === 'PUT') return favorite(request, env, decodeURIComponent(url.pathname.slice(15)), user); if (url.pathname.startsWith('/api/cart/') && request.method === 'PUT') return cart(request, env, decodeURIComponent(url.pathname.slice(10)), user); if (url.pathname === '/api/orders' && request.method === 'POST') return order(request, env, user); return null } catch (error) { return json({ message: error instanceof Error ? error.message : '共享数据暂时无法处理。' }, 500) } }
export async function serveMedia(_request, env, url) { if (!env.MEDIA) return json({ message: '图片存储尚未绑定。' }, 503); const key = decodeURIComponent(url.pathname.slice('/api/media/'.length)); if (!/^[a-zA-Z0-9._-]+$/.test(key)) return json({ message: '图片地址无效。' }, 400); const object = await env.MEDIA.get(key); if (!object) return json({ message: '图片不存在。' }, 404); const headers = new Headers(); object.writeHttpMetadata(headers); headers.set('ETag', object.httpEtag); headers.set('Cache-Control', 'private, max-age=3600'); return new Response(object.body, { headers }) }
